# Generated by Django 6.0.2 on 2026-02-08 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firmy_django', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='firma',
            name='name',
        ),
        migrations.AddField(
            model_name='firma',
            name='nazwa',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='firma',
            name='kwota',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='firma',
            name='nip',
            field=models.CharField(blank=True, default='0000000000', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='firma',
            name='plik',
            field=models.TextField(blank=True, default=''),
            preserve_default=False,
        ),
    ]
