# Generated by Django 6.0.2 on 2026-02-08 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firmy_django', '0002_remove_firma_name_firma_nazwa_alter_firma_kwota_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='firma',
            name='kwota',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='firma',
            name='nazwa',
            field=models.CharField(default='brak', max_length=255),
        ),
        migrations.AlterField(
            model_name='firma',
            name='nip',
            field=models.CharField(blank=True, default='brak', max_length=20),
        ),
        migrations.AlterField(
            model_name='firma',
            name='plik',
            field=models.CharField(blank=True, default='brak', max_length=255),
        ),
    ]
