# Generated by Django 6.0.2 on 2026-06-01 17:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firmy_django', '0003_alter_firma_kwota_alter_firma_nazwa_alter_firma_nip_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='firma',
            name='kwota',
        ),
        migrations.RemoveField(
            model_name='firma',
            name='plik',
        ),
        migrations.AddField(
            model_name='firma',
            name='miasto',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='firma',
            name='regon',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='firma',
            name='nazwa',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='firma',
            name='nip',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.CreateModel(
            name='SprawozdanieFinansowe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rok', models.PositiveIntegerField()),
                ('naleznosci', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('aktywa', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('przychody', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('zysk_netto', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('plik_xml', models.CharField(blank=True, max_length=255)),
                ('firma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sprawozdania', to='firmy_django.firma')),
            ],
            options={
                'ordering': ['-rok'],
                'unique_together': {('firma', 'rok')},
            },
        ),
    ]
