# Generated by Django 6.0.2 on 2026-06-04 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firmy_django', '0004_remove_firma_kwota_remove_firma_plik_firma_miasto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='firma',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='firma',
            name='email_zrodlo',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
