# Generated by Django 6.0.2 on 2026-06-04 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firmy_django', '0005_firma_email_firma_email_zrodlo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='firma',
            name='email_zrodlo',
            field=models.CharField(blank=True, choices=[('', 'Brak'), ('recznie', 'Ręcznie'), ('xml', 'XML'), ('strona_www', 'Strona internetowa'), ('ceidg', 'CEIDG / biznes.gov.pl'), ('gus_regon', 'GUS REGON'), ('krs', 'KRS'), ('inne', 'Inne')], max_length=50),
        ),
    ]
