# Generated by Django 6.0.2 on 2026-06-04 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firmy_django', '0006_alter_firma_email_zrodlo'),
    ]

    operations = [
        migrations.AddField(
            model_name='firma',
            name='email_zrodlo_opis',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
