# Generated by Django 6.0.2 on 2026-06-05 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firmy_django', '0007_firma_email_zrodlo_opis'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mailing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temat', models.CharField(max_length=255)),
                ('tresc', models.TextField()),
                ('liczba_odbiorcow', models.IntegerField()),
                ('data_wyslania', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
