# Generated by Django 6.0.2 on 2026-06-05 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firmy_django', '0008_mailing'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailing',
            name='liczba_dodatkowych_odbiorcow',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='mailing',
            name='liczba_firm_z_bazy',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='mailing',
            name='odbiorcy',
            field=models.TextField(blank=True),
        ),
    ]
