# Generated by Django 6.0.2 on 2026-06-07 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firmy_django', '0011_mailing_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='firma',
            name='krs',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
