# Generated by Django 6.0.2 on 2026-06-15 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firmy_django', '0012_firma_krs'),
    ]

    operations = [
        migrations.AddField(
            model_name='sprawozdaniefinansowe',
            name='czy_zarchiwizowane',
            field=models.BooleanField(default=False),
        ),
    ]
