# Generated by Django 6.0.2 on 2026-06-30 17:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firmy_django', '0013_sprawozdaniefinansowe_czy_zarchiwizowane'),
    ]

    operations = [
        migrations.CreateModel(
            name='Branza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='firma',
            name='branze',
            field=models.ManyToManyField(blank=True, related_name='firmy', to='firmy_django.branza'),
        ),
        migrations.CreateModel(
            name='ProfilFirmy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opis_dzialalnosci', models.TextField(blank=True)),
                ('strona_www', models.URLField(blank=True)),
                ('telefon', models.CharField(blank=True, max_length=30)),
                ('firma', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profil', to='firmy_django.firma')),
            ],
        ),
    ]
