# Generated by Django 6.0.2 on 2026-07-03 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firmy_django', '0014_branza_firma_branze_profilfirmy'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='sprawozdaniefinansowe',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='sprawozdaniefinansowe',
            name='plik_xml',
            field=models.FileField(blank=True, upload_to='sprawozdania_xml/importy/'),
        ),
        migrations.AddConstraint(
            model_name='sprawozdaniefinansowe',
            constraint=models.UniqueConstraint(fields=('firma', 'rok'), name='unique_sprawozdanie_firma_rok'),
        ),
    ]
