# Generated by Django 6.0.2 on 2026-07-06 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firmy_django', '0015_alter_sprawozdaniefinansowe_unique_together_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mailing',
            old_name='odbiorcy',
            new_name='odbiorcy_zewnetrzni',
        ),
        migrations.RenameField(
            model_name='profilfirmy',
            old_name='opis_dzialalnosci',
            new_name='opis',
        ),
        migrations.RemoveField(
            model_name='mailing',
            name='liczba_dodatkowych_odbiorcow',
        ),
        migrations.RemoveField(
            model_name='mailing',
            name='liczba_firm_z_bazy',
        ),
        migrations.RemoveField(
            model_name='mailing',
            name='liczba_odbiorcow',
        ),
        migrations.RemoveField(
            model_name='profilfirmy',
            name='strona_www',
        ),
        migrations.RemoveField(
            model_name='profilfirmy',
            name='telefon',
        ),
        migrations.AddField(
            model_name='firma',
            name='strona_www',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='firma',
            name='telefon',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='mailing',
            name='firmy_odbiorcy',
            field=models.ManyToManyField(blank=True, related_name='mailingi', to='firmy_django.firma'),
        ),
        migrations.AddField(
            model_name='profilfirmy',
            name='banner',
            field=models.FileField(blank=True, upload_to='profile_firm/bannery/'),
        ),
        migrations.AddField(
            model_name='profilfirmy',
            name='logo',
            field=models.FileField(blank=True, upload_to='profile_firm/loga/'),
        ),
    ]
