# Generated by Django 6.0.2 on 2026-07-27 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firmy_django', '0016_rename_odbiorcy_mailing_odbiorcy_zewnetrzni_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilfirmy',
            name='strona_www',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='profilfirmy',
            name='telefon',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
